examples:
  - examples/*
  - examples/**/*

html-to-slate-ast:
  - packages/html-to-slate-ast/*
  - packages/html-to-slate-ast/**/*

react-renderer:
  - packages/react-renderer/*
  - packages/react-renderer/**/*

types:
  - packages/types/*
  - packages/types/**/*

repo:
  - ./*
